const CAMPAIGN_CREATION_COST = 348;

const USER_TYPE = {
  INFLUENCER: 'INFLUENCER',
  BRAND: 'BRAND',
};

const BOOKING_STATE = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETE: 'COMPLETE',
  APPLIED: 'APPLIED',
  REQUESTED: 'REQUESTED',
};

const PAYMENT_REASON = {
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  ACCEPT_BOOKING: 'ACCEPT_BOOKING',
};

module.exports = {
  CAMPAIGN_CREATION_COST,
  USER_TYPE,
  BOOKING_STATE,
  PAYMENT_REASON,
};
