const USER_TYPE = {
  INFLUENCER: 'INFLUENCER',
  BRAND: 'BRAND',
};

const BOOKING_STATE = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETE: 'COMPLETE',
  APPLIED: 'APPLIED',
  REQUESTED: 'REQUESTED',
};

module.exports = {
  USER_TYPE,
  BOOKING_STATE,
};
