const CAMPAIGN_CREATION_COST = 348;
const BOOKING_APPLICATION_FEE = 0.08; // Percent
const STRIPE_CONNECT_ACCOUNT_CHARGE = 200;

const USER_TYPE = {
  INFLUENCER: 'INFLUENCER',
  BRAND: 'BRAND',
};

const BOOKING_STATE = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETE: 'COMPLETE',
  APPLIED: 'APPLIED',
  REQUESTED: 'REQUESTED',
};

const BUDGET_TYPE = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
};

const PAYMENT_REASON = {
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  ACCEPT_BOOKING: 'ACCEPT_BOOKING',
};

module.exports = {
  CAMPAIGN_CREATION_COST,
  BOOKING_APPLICATION_FEE,
  STRIPE_CONNECT_ACCOUNT_CHARGE,
  USER_TYPE,
  BOOKING_STATE,
  BUDGET_TYPE,
  PAYMENT_REASON,
};
