type Query {
  user: User @resolver(name: "current_user")
  # Discover campaigns listing
  discover: [Campaign] @index(name: "campaigns")
  # Campaigns listing
  campaigns: [Campaign]
    @resolver(name: "campaigns_by_user_type", paginated: true)

  findCampaignByID(id: ID): Campaign @resolver(name: "find_campaign_by_id")

  # Inbox threads
  threads: [Thread] @resolver(name: "threads", paginated: true)
  threadMessages(threadId: ID!): [Message]
    @resolver(name: "messages", paginated: true)
}

type Mutation {
  login(email: String!, password: String!): Auth @resolver(name: "user_login")
  register(email: String!, password: String!, type: UserType!): Auth
    @resolver(name: "register")
  createMessage(threadId: ID!, text: String!): Message
    @resolver(name: "create_message")
  createCampaign(
    name: String!
    description: String!
    dueDate: String!
    private: Boolean!
    budget: String!
  ): Campaign @resolver(name: "create_campaign")
}

type Auth @embedded {
  secret: String!
}

type Media @embedded {
  url: String!
}

enum UserType {
  BRAND
  INFLUENCER
}

type User {
  name: String
  avatar: Media
  email: String! @unique

  type: UserType!

  # User created Campaigns
  campaigns: [Campaign] @relation

  # User applications/requests to
  # join Campaigns
  bookings: [Booking] @relation

  threads: [Thread] @relation
}

type Campaign {
  # the brand who created the campaign
  user: User

  name: String
  description: String
  dueDate: Date
  private: Boolean
  budget: Float
  bookings: [Booking] @relation
  userBooking: Booking @embedded
}

enum BookingState {
  ACCEPTED
  DECLINED
  COMPLETE

  # For when an influencer applies
  # to a campaign
  APPLIED

  # For when an brand requests
  # an influencer onto a campaign
  REQUESTED
}

type Booking {
  campaign: Campaign! @relation
  user: User!
  cost: Float!
  state: BookingState!
}

type Thread {
  users: [User] @relation
  messages: [Message] @relation
  latestMessage: Message @embedded
}

type Message {
  date: Date!
  thread: Thread! @relation
  user: User!
  text: String!
}
