export const NETWORK_STATUS = {
  FETCHING: 1,
  SET_VARIABLES: 2,
  FETCH_MORE: 3,
  REFETCHING: 4,
  POLL: 6,
  READY: 7,
  ERROR: 8,
};

export const FORM_ERROR_MESSAGES = {
  INVALID_EMAIL: 'Please enter a valid email',
  REQUIRED_PASSWORD: 'We need you to set a password',
  REQUIRED_EMAIL: 'We need your email',
  INVALID_NUMBER: 'Please enter a valid budget amount',
  MIN_BUDGET: 'Budget must be more than £5.00',
};

export const USER_TYPE = {
  INFLUENCER: 'INFLUENCER',
  BRAND: 'BRAND',
};

export const CAMPAIGN_TYPE = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

export const BOOKING_STATE = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETE: 'COMPLETE',
  APPLIED: 'APPLIED',
  REQUESTED: 'REQUESTED',
};

export const MODAL_TYPES = {
  CAMPAIGN_CREATION: 'CAMPAIGN_CREATION',
  CONFIRM_REQUEST_INFLUENCERS: 'CONFIRM_REQUEST_INFLUENCERS',
  WEB_VIEW_MODAL: 'WEB_VIEW_MODAL',
  CONFIRM_REQUESTED_INFLUENCER_TO_CAMPAIGNS:
    'CONFIRM_REQUESTED_INFLUENCER_TO_CAMPAIGNS',
  CONFIRM_PAYMENT: 'CONFIRM_PAYMENT',
};

export const ACTION_COMPONENTS = {
  ADD_REMOVE: 'ADD_REMOVE',
};
