export const CLOUDINARY_UPLOAD_URL =
  'https://api.cloudinary.com/v1_1/peach-app/image/upload';

export const CLOUDINARY_PRESET = 'u4mzj2ke';

export const NETWORK_STATUS = {
  FETCHING: 1,
  SET_VARIABLES: 2,
  FETCH_MORE: 3,
  REFETCHING: 4,
  POLL: 6,
  READY: 7,
  ERROR: 8,
};

export const USER_TYPE = {
  INFLUENCER: 'INFLUENCER',
  BRAND: 'BRAND',
};

export const CAMPAIGN_TYPE = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

export const BUDGET_TYPE = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
};

export const BOOKING_STATE = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETE: 'COMPLETE',
  APPLIED: 'APPLIED',
  REQUESTED: 'REQUESTED',
};

export const PAYMENT_REASON = {
  ACCEPT_BOOKING: 'ACCEPT_BOOKING',
};

export const MODAL_TYPES = {
  CAMPAIGN_CREATION: 'CAMPAIGN_CREATION',
  CONFIRM_REQUEST_INFLUENCERS: 'CONFIRM_REQUEST_INFLUENCERS',
  WEB_VIEW_MODAL: 'WEB_VIEW_MODAL',
  CONFIRM_REQUESTED_INFLUENCER_TO_CAMPAIGNS:
    'CONFIRM_REQUESTED_INFLUENCER_TO_CAMPAIGNS',
  CONFIRM_PAYMENT: 'CONFIRM_PAYMENT',
  CAMPAIGN_APPLY: 'CAMPAIGN_APPLY',
};

export const ACTION_COMPONENTS = {
  ADD_REMOVE: 'ADD_REMOVE',
};
